apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: efk-stack
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    http:
      enabled: true
      host: "127.0.0.1"
      port: 5066
    
    filebeat.inputs:
    - type: filestream
      id: kubernetes-container-logs
      paths:
        - /var/log/containers/*.log
      parsers:
        - container: ~
      prospector:
        scanner:
          symlinks: true
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ["http://elasticsearch.efk-stack:9200"]
