apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: efk-stack
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: http
  selector:
    app: kibana
  type: ClusterIP