apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: efk-stack
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    app: elasticsearch
