apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: hello-world
spec:
  selector:
    app: nginx
    component: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP